config/routes.rb
Task6::Application.routes.draw do
  devise_for :users

  root :to => "playlists#index"
  resources :playlists do
    collection do
      get :search
    end
  end

end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
    belongs_to :user
    validates :name, :presence => true
    validates :user_id, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  has_many :playlists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController

    before_filter :authenticate_user!, :except => [:index, :search]
    attr_reader :per_page
    #@@per_page = 3
    
    
    def index
        @playlists  = Playlist.all
        @playlists  = @playlists.paginate(:page => params[:page], :per_page => 2)
    end
    
    def new
        @playlist = Playlist.new
    end
    
    def create
      @playlist = Playlist.new(params[:playlist])
      @playlist.update_attributes(:user_id => current_user.id)
      if @playlist.save
          redirect_to playlists_path
      else
          render :action => :new
      end
    end
    
    def search
        @playlists         = Playlist.search( params[:search] )
        #@playlists      = @search.paginate(:page => params[:page], :per_page => 2)
    end
    
    def show
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Task6</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<div id="user_nav">
  <% if user_signed_in? %>
    Signed in as <%= current_user.email %>. Not you?
    <%= link_to "Sign out", destroy_user_session_path %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
  <% end %>
</div>

</body>
</html>

app/views/playlists/_form.html.haml
= f.error_messages
%p
    Nazwa
    %br
    = f.text_field :name
    %br
    Autor
    %br
    = f.text_field :author
    %br
    Playlista
    %br
    = f.text_area :list
    %br
    Data
    %br
    = f.date_select :date
  
%p=f.submit "Dodaj"

app/views/playlists/_list.html.haml
%h3
    = playlist.name
%p
    = playlist.author
%p
    = playlist.list

app/views/playlists/index.html.haml
%p= link_to "Utwórz", new_playlist_path
%p= link_to "Wyszukaj", search_playlists_path


- @playlists.each do |playlist|
    = render :partial => "list", :locals => {:playlist => playlist}


= will_paginate @playlists    
%hr

app/views/playlists/new.html.haml
- form_for @playlist do |f|
  = render :partial => 'form', :locals => {:f => f}
%p= link_to "Powrót", playlists_path

app/views/playlists/search.html.haml
%p= link_to "Powrót", playlists_path

- @playlists.each do |playlist|
  = render :partial => "list", :locals => {:playlist => playlist}


%hr

= form_for :search, :as => @search, :html => {:method => :get} do |f|
  %p
    = f.label :list_contains
    = f.text_field :list_contains
    =# f.label :comments_created_at_greater_than, 'With comments after'
    =# f.datetime_select :comments_created_at_greater_than, :include_blank => true %><br />
    = f.submit 